### ISSUE TITLE
Can't setup over-the-internet streaming

### ISSUE THREAD

**Issue by joaovittorsc** [moonlight-stream/Internet-Streaming-Helper#5]
It says that my router is connected to the internet through another one, wich isn't the case. Here's my log:

Moonlight Internet Streaming Tester v2.1.0.0
GeForce Experience installed and GameStream is enabled
Testing GameStream ports via loopback
Testing TCP 47984...Success
Testing TCP 47989...Success
Testing TCP 48010...Success
Testing UDP 47998...Success
Testing UDP 47999...Unknown (in use)
Testing UDP 48000...Success
Testing UDP 48002...Success
Testing UDP 48010...Unknown (in use)
Finding local IP address...10.0.0.100
Testing GameStream ports via local network
Testing TCP 47984...Success
Testing TCP 47989...Success
Testing TCP 48010...Success
Testing UDP 47998...Success
Testing UDP 47999...Unknown (in use)
Testing UDP 48000...Success
Testing UDP 48002...Success
Testing UDP 48010...Unknown (in use)
Discovered UPnP IGD at: http://10.0.0.1:5431/control/WANIPConnection
Detecting WAN IP address via UPnP...192.168.2.2
Checking for UPnP port mapping for TCP 47984 -> 10.0.0.100...NOT FOUND
Checking for UPnP port mapping for TCP 47989 -> 10.0.0.100...NOT FOUND
Checking for UPnP port mapping for TCP 48010 -> 10.0.0.100...NOT FOUND
Checking for UPnP port mapping for UDP 47998 -> 10.0.0.100...NOT FOUND
Checking for UPnP port mapping for UDP 47999 -> 10.0.0.100...NOT FOUND
Checking for UPnP port mapping for UDP 48000 -> 10.0.0.100...NOT FOUND
Checking for UPnP port mapping for UDP 48002 -> 10.0.0.100...NOT FOUND
Checking for UPnP port mapping for UDP 48010 -> 10.0.0.100...NOT FOUND
Detecting WAN IP address via NAT-PMP...FAILED -5
Detecting WAN IP address via STUN...186.226.202.87
Testing GameStream ports via UPnP/NAT-PMP reported WAN address
Testing TCP 47984...Timeout
Testing TCP 47989...Timeout
Testing TCP 48010...Timeout
Testing UDP 47998...Timeout
Testing UDP 47999...Unknown (in use)
Testing UDP 48000...Timeout
Testing UDP 48002...Timeout
Testing UDP 48010...Unknown (in use)
Detected inconsistency between UPnP/NAT-PMP and STUN reported WAN addresses!
Testing GameStream ports via STUN-reported WAN address
Testing TCP 47984...Timeout
Testing TCP 47989...Timeout
Testing TCP 48010...Timeout
Testing UDP 47998...Timeout
Testing UDP 47999...Unknown (in use)
Testing UDP 48000...Timeout
Testing UDP 48002...Timeout
Testing UDP 48010...Unknown (in use)
Your router appears be connected to the Internet through another router. Make sure both routers have UPnP or NAT-PMP enabled, or better yet, switch one of the routers into bridge/AP mode.
--------------- MISS LOG -------------------
Moonlight Internet Streaming Service v2.1.0.0
Woke up for periodic refresh
GameStream is ON!
Finding upstream IPv4 hops via traceroute...
IcmpSendEcho() failed: 11010
Found 0 hops
Starting port mapping update on default gateway to local machine...
UPnP IPv4 IGD discovery completed with error code: 0
NAT-PMP public address request failed: -5
Found a disconnected UPnP IGD (!)
UPnP IGD WAN address is: 192.168.2.2
Checking for existing UPnP port mapping for TCP 47984 -> 10.0.0.100 DESKTOP-5KUKST9...NOT FOUND
Updating UPnP port mapping for TCP 47984 -> 10.0.0.100...OK
Checking for existing UPnP port mapping for TCP 47989 -> 10.0.0.100 DESKTOP-5KUKST9...NOT FOUND
Updating UPnP port mapping for TCP 47989 -> 10.0.0.100...OK
Checking for existing UPnP port mapping for TCP 48010 -> 10.0.0.100 DESKTOP-5KUKST9...NOT FOUND
Updating UPnP port mapping for TCP 48010 -> 10.0.0.100...OK
Checking for existing UPnP port mapping for UDP 47998 -> 10.0.0.100 DESKTOP-5KUKST9...NOT FOUND
Updating UPnP port mapping for UDP 47998 -> 10.0.0.100...OK
Checking for existing UPnP port mapping for UDP 47999 -> 10.0.0.100 DESKTOP-5KUKST9...NOT FOUND
Updating UPnP port mapping for UDP 47999 -> 10.0.0.100...OK
Checking for existing UPnP port mapping for UDP 48000 -> 10.0.0.100 DESKTOP-5KUKST9...NOT FOUND
Updating UPnP port mapping for UDP 48000 -> 10.0.0.100...OK
Checking for existing UPnP port mapping for UDP 48002 -> 10.0.0.100 DESKTOP-5KUKST9...NOT FOUND
Updating UPnP port mapping for UDP 48002 -> 10.0.0.100...OK
Checking for existing UPnP port mapping for UDP 48010 -> 10.0.0.100 DESKTOP-5KUKST9...NOT FOUND
Updating UPnP port mapping for UDP 48010 -> 10.0.0.100...OK
Checking for existing UPnP port mapping for UDP 9 -> 10.255.255.255 DESKTOP-5KUKST9...OK (Permanent)
Updating UPnP port mapping for UDP 9 -> 10.255.255.255...ERROR 720 (UnknownError)
Updating PCP port mapping for TCP 47984...NO RESPONSE
Updating PCP port mapping for TCP 47989...NO RESPONSE
Updating PCP port mapping for TCP 48010...NO RESPONSE
Updating PCP port mapping for UDP 47998...NO RESPONSE
Updating PCP port mapping for UDP 47999...NO RESPONSE
Updating PCP port mapping for UDP 48000...NO RESPONSE
Updating PCP port mapping for UDP 48002...NO RESPONSE
Updating PCP port mapping for UDP 48010...NO RESPONSE
Using UPnP upstream IPv4 address: 192.168.2.2
Upstream address 192.168.2.2 is likely a NAT
Traceroute didn't reach this hop! Aborting!
Going to sleep...

**Comment by topongo** [comment]
same problem I have a fritz.box owned by my ips and a Dlink DIR-878 A1 with DD-WRT installed

**Comment by topongo** [comment]
please anyone can help us?

**Comment by cgutman** [comment]
What steps have you tried to resolve the issue?

**Comment by cgutman** [comment]
Closing this issue. Please use Discord chat for troubleshooting your network setup rather than GitHub issues.
